doc/source/getting_started/docker.rst
=> fix: broken link

.github/workflows/ci_cd.yml, .github/workflows/nightly_docker_test.yml
=> feat: skip unstable images temporarily

.github/workflows/ci_cd.yml, README.rst
=> feat: proper codecov badge

doc/make.bat
=> feat: change source of sphinx-autoapi repo

src/ansys/geometry/core/connection/launcher.py
=> docs: error on docstrings for launcher methods

doc/source/getting_started/compatibility.rst, doc/source/getting_started/docker/index.rst, doc/source/getting_started/faq.rst, doc/source/getting_started/index.rst, doc/styles/Vocab/ANSYS/accept.txt
=> docs: improve getting started

.github/workflows/ci_cd.yml, doc/source/conf.py
=> doc: enhance search engine using pymeilisearch 

.github/labels.yml, SECURITY.md
=> feat: adding SECURITY policy

.github/workflows/codeql.yml
As title says - this is part of the vulnerability check improvements
=> feat: add CodeQL analysis

doc/source/getting_started/faq.rst
=> feat: add license discussion to Q&A

.github/workflows/codeql.yml
As title says. Pinging @AlejandroFernandezLuces for review
=> cicd: cleanup CodeQL workflow

.github/workflows/ci_cd.yml, .github/workflows/docker_test_build.yml, .github/workflows/nightly_docker_test.yml, README.rst, doc/source/assets.rst, doc/source/conf.py, doc/source/getting_started/installation.rst, pyproject.toml, src/ansys/geometry/core/__init__.py, src/ansys/geometry/core/logger.py, tox.ini
As title says
Also, defining 3.11 as the main Python version
=> feat: drop Python 3.8 and setting main version as 3.11

.github/workflows/ci_cd.yml, .github/workflows/docker_test_build.yml, .github/workflows/nightly_docker_test.yml, tests/conftest.py, tests/integration/conftest.py, tests/integration/test_design.py, tests/integration/test_design_import.py
=> feat: proper service-based testing

.github/workflows/ci_cd.yml, tests/integration/test_design_import.py
=> cicd: reacitvate Linux testing

tests/integration/test_design.py
=> feat: reactivate PMDB export

.github/workflows/ci_cd.yml, doc/.vale.ini, doc/source/assets.rst, doc/source/getting_started/faq.rst, doc/styles/Vocab/ANSYS/accept.txt
This PR is to reactivate vale and fix any error that might arise
=> maint: Reactivate style action

README.rst
=> feat: simplifying README

doc/source/index.rst
=> fix: typo in docs

codecov.yml
As title says. Removing patch behavior
=> feat: add codecov.yml file

doc/source/assets.rst
=> fix: install wheelhouse on Windows

doc/source/getting_started/index.rst
I thought that it could have an added value to quickly see how to install the package when starting to look at the `getting started`.
=> Add an installation section to the getting started.

.github/workflows/docker_ansyslab_linux.yml, .github/workflows/docker_ansyslab_windows.yml, .github/workflows/docker_push_stable.yml
As title says. Allows to deploy to AnsysLab much faster.
=> feat: breakup AnsysLab deployment

doc/Makefile, pyproject.toml
As title says - following @jorgepiloto's recommendation on upcoming Numpy major release and applying to all deps
=> feat: protecting deps installed on upper limits

src/ansys/geometry/core/connection/product_instance.py
=> feat: allowing student versions

doc/source/getting_started/existing/index.rst, doc/source/getting_started/local/index.rst
Minor improvements on documentation
=> docs: various improvements

.pre-commit-config.yaml, doc/source/getting_started/docker/windows_container.rst, docker/README.rst, docker/build_docker_windows.py
=> feat: provide script to build your own Geometry Service Docker image

doc/source/getting_started/docker/windows_container.rst, src/ansys/geometry/core/connection/product_instance.py
=> feat: check if ApiServer Add-In exists before executing

doc/source/conf.py, doc/source/index.rst
=> feat: readapt landing page

pyproject.toml
=> maint: update Sphinx

.github/workflows/dependabot_automerge.yml
As title says. Squash and merge failing
Trying
https://github.com/cli/cli/discussions/5351#discussioncomment-2865049
https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows
=> fix: automerge

.github/workflows/dependabot_automerge.yml
Fixes issues when merging & approving
=> fix: approval needs to be done by CI bot

README.rst
=> docs: add downloads badge

.github/workflows/ci_cd.yml
As per a private discussion, this is setup to avoid creating the default sitemap.xml file.
=> feat: seo-improvements

.github/codeql-config.yml, .github/workflows/codeql.yml
=> maint: fix CodeQL config issues

README.rst, src/ansys/geometry/core/connection/product_instance.py, src/ansys/geometry/core/designer/part.py, src/ansys/geometry/core/misc/auxiliary.py, src/ansys/geometry/core/misc/checks.py, src/ansys/geometry/core/sketch/edge.py, src/ansys/geometry/core/sketch/face.py
As title says. Related to #978
=> feat: properly allow SpaceClaim to run in hidden mode

doc/source/conf.py, doc/source/contributing.rst, doc/source/getting_started/existing/index.rst, doc/source/index.rst, doc/styles/Vocab/ANSYS/accept.txt
=> docs: improve contributing section

.github/workflows/ci_cd.yml, doc/source/getting_started/docker/windows_container.rst, docker/build_docker_windows.py
As title says - following up on #902
=> fix: renaming Dockerfiles

doc/make.bat, doc/source/conf.py, doc/source/getting_started/docker/windows_container.rst, doc/source/getting_started/faq.rst
Many FAQs have come along recently on how to build Docker containers, install the Ansys Geometry service and so on. This solves these requests
#1022 for example
=> docs: adding recent faqs

.github/pull_request_template.md, pyproject.toml, src/ansys/geometry/core/connection/client.py, src/ansys/geometry/core/designer/body.py, src/ansys/geometry/core/misc/__init__.py, src/ansys/geometry/core/misc/checks.py, tests/test_misc_checks.py
Add a minimum version decorator to allow checking if methods are compatible with the current backend.
#1004
=> feat: Add min_backend_version decorator

src/ansys/geometry/core/designer/body.py, src/ansys/geometry/core/modeler.py, src/ansys/geometry/core/tools/measurement_tools.py, tests/integration/test_logging_client.py
Adding decorator to missing methods included in 24R2
Related to #1024 - follow-up
=> feat: adding version checks to new 24R2 APIs

doc/make.bat
=> docs: re-enable linkcheck

doc/source/index.rst
The name on this card didn't match the section name, which it should. The icon showing downloads is still appropriate, but the two names should match.
**Please provide a brief description of the changes made in this pull request.**
=> docs: update index.rst

src/ansys/geometry/core/designer/__init__.py, src/ansys/geometry/core/designer/component.py, tests/integration/test_design.py
Allowing extrusion of a sketch and face in positive and negative z direction
Closes #1041
=> feat: add extrude in pos/neg direction

doc/source/conf.py
Removing unnecessary flag
No issue
=> docs: remove check switcher

.pre-commit-config.yaml, doc/changelog.d/1064.miscellaneous.md, doc/changelog.d/1065.changed.md
Provide pre-commit-ci configuration
-
=> chore: add pre-commit.ci configuration

.github/workflows/dependabot_automerge.yml, doc/changelog.d/1067.changed.md, doc/styles/Vocab/ANSYS/accept.txt
=> chore: dependabot PR automatic approval

doc/changelog.d/1069.fixed.md, docker/linux/Dockerfile
**Please provide a brief description of the changes made in this pull request.**
=> fix: linux Dockerfile - replace .NET6.0 references by .NET8.0

.github/workflows/ci_cd.yml, doc/changelog.d/1071.added.md
Implementing vulnerability checks in PyAnsys Geometry
=> feat: vulnerability checks

doc/changelog.d/1077.added.md, src/ansys/geometry/core/connection/product_instance.py
Accept bandit advisories relative to using subprocess since they have been verified and protected for safe usage
=> feat: accept bandit advisories in-line for subprocess

.github/workflows/docker_cleanup.yml, doc/changelog.d/1085.changed.md
=> chore: update docker tags to be kept

doc/changelog.d/1090.added.md, src/ansys/geometry/core/connection/docker_instance.py
Adding new version containers to the enum
None
=> feat: adding containers to automatic launcher

doc/changelog.d/1096.fixed.md, src/ansys/geometry/core/designer/body.py, tests/integration/test_design.py
Identified by @b-matteo and @rajesh1359 . Issue is related to ``project_curves`` and ``imprint_curves``. Faces and edges created are malformed since the surface type and curve type are not passed properly.
None
=> fix: improper types being passed for Face and Edge ctor.

doc/changelog.d/1097.changed.md, pyproject.toml
Use the ``ansys-sphinx-theme`` "autoapi" target.
=> build: use ansys-sphinx-theme "autoapi" target

.github/workflows/ci_cd.yml, .pre-commit-config.yaml, doc/changelog.d/1108.changed.md
=> chore: pre-commit.ci not working properly

.pre-commit-config.yaml, doc/changelog.d/1109.changed.md
Adding pre-commit.ci config hook + update of other hook versions
None
=> chore: update and adding pre-commit.ci config hook

doc/changelog.d/1111.added.md, docker/linux/Dockerfile
Linux Dockerfile was updated to include extra dependencies
None
=> feat: minor changes to Linux Dockerfile

doc/changelog.d/1113.changed.md, tests/integration/conftest.py, tests/integration/test_design.py, tests/integration/test_material.py, tests/integration/test_plotter.py, tests/integration/test_tessellation.py
=> ci: skip Linux tests with common approach

doc/changelog.d/1120.fixed.md, docker/windows/Dockerfile
Fix env variable for Windows Dockerfile
=> fix: env version for Dockerfile Windows

CHANGELOG.md, doc/changelog.d/1121.fixed.md
As title says. Issues with docstring
=> fix: changelog description ill-formatted

SECURITY.md, doc/changelog.d/1126.added.md, doc/source/examples/01_getting_started/04_modeling.mystnb, doc/source/getting_started/compatibility.rst, src/ansys/geometry/core/connection/launcher.py
Security fixes are dropped for v0.3 and earlier
None
=> feat: security updates dropped for v0.3 or earlier

doc/changelog.d/1137.fixed.md, doc/source/examples/03_modeling/plate_with_hole.mystnb
=> fix: docs link in example

.pre-commit-config.yaml, LICENSE, doc/changelog.d/1139.changed.md
=> chore: bump ansys pre-commit hook to ``v0.3.0``

doc/changelog.d/1142.changed.md, doc/source/conf.py
Using ``user_agent`` to avoid bot-style issues on certain web pages (mostly related to linkcheck)
=> docs: add ``user_agent`` to Sphinx build

doc/changelog.d/1145.fixed.md, src/ansys/geometry/core/misc/checks.py, tests/test_misc_checks.py
Include a more informative message regarding the problems related to the backend version.
Closes #1143
=> fix: update backend version message

doc/changelog.d/1152.changed.md, tests/integration/test_design.py, tests/integration/test_material.py, tests/integration/test_plotter.py, tests/integration/test_tessellation.py
=> ci: enabling Linux tests missing

.github/workflows/ci_cd.yml, doc/changelog.d/1166.changed.md, doc/source/assets.rst, doc/source/getting_started/installation.rst, pyproject.toml
=> chore: bump version to v0.6.dev0

README.rst, doc/changelog.d/1169.miscellaneous.md
=> docs: simplify README example

doc/changelog.d/1175.fixed.md, src/ansys/geometry/core/connection/client.py
As title says. Follow up of #1173
=> fix: semver intersphinx mapping not resolved properly

SECURITY.md, doc/changelog.d/1214.changed.md
=> chore: update SECURITY.md

.github/workflows/ci_cd.yml, .github/workflows/nightly_docker_test.yml, doc/changelog.d/1221.changed.md
=> ci: remove pygeometry-ci-1 specific logic

.github/workflows/ci_cd.yml, .github/workflows/nightly_docker_test.yml, doc/changelog.d/1230.added.md, doc/source/conf.py, tests/integration/conftest.py
After the usage of global vars was fixed, it is best if we stick to them.
None
=> refactor: use ansys-tools-visualization-interface global vars rather than env vars

.github/workflows/nightly_docker_test.yml, doc/changelog.d/1237.changed.md
Notify via Teams channel of nightly workflows failing
Closes #1209
=> ci: announce nightly workflows failing

.github/workflows/nightly_docker_test.yml, doc/changelog.d/1238.fixed.md
=> fix: only notify on failure and fill with data

.github/workflows/nightly_docker_test.yml, doc/changelog.d/1243.changed.md
Improving message description
No issue linked
=> ci: failing notifications improvement

README.rst, doc/changelog.d/1247.miscellaneous.md, doc/source/getting_started/installation.rst, doc/styles/config/vocabularies/ANSYS/accept.txt
Once published on conda-forge (see https://github.com/conda-forge/staged-recipes/pull/26585) we will be able to refer to it.
Closes #1229
=> docs: add conda information for package

.github/workflows/ci_cd.yml, doc/changelog.d/1262.changed.md
Following enhancements to actions implemented by @SMoraisAnsys, migrate to using ``ansys/actions/doc-build``
No issue
=> ci: simplify doc build using ansys/actions

.github/workflows/ci_cd.yml, doc/Makefile, doc/changelog.d/1268.fixed.md, doc/make.bat, doc/source/conf.py, pyproject.toml
Reported by @jorgepiloto - for some reason the example Python files and Jupyter NBs are not uploaded... investigating
=> docs: examples are not being uploaded as assets (.py/.ipynb)

.github/workflows/ci_cd.yml, doc/changelog.d/1269.fixed.md
=> fix: change action order

.github/workflows/ci_cd.yml, doc/changelog.d/1270.changed.md
As title says - follow up from #1269 #1262 and many others...
=> docs: using ansys actions (again) to build docs

doc/changelog.d/1280.changed.md, pyproject.toml
Fix branch name from #1279
Updating package
=> build: update sphinx-autodoc-typehints version

.github/workflows/docker_cleanup.yml, doc/changelog.d/1294.fixed.md
=> ci: docker cleanup

SECURITY.md, doc/changelog.d/1361.maintenance.md, doc/source/assets.rst, doc/source/changelog.rst, doc/source/getting_started/installation.rst, pyproject.toml
Updating main branch for v0.8.dev0
=> chore: bump dev branch to v0.8.dev0

doc/changelog.d/1368.maintenance.md, src/ansys/geometry/core/designer/body.py, src/ansys/geometry/core/materials/material.py, src/ansys/geometry/core/misc/checks.py, src/ansys/geometry/core/sketch/trapezoid.py, src/ansys/geometry/core/typing.py
As title says - tests were raising several warnings.
None
=> chore: solving various warnings

.github/workflows/ci_cd.yml, doc/changelog.d/1406.maintenance.md
=> ci: upload coverage artifacts properly with upload-artifact@v4.4.0

.github/workflows/ci_cd.yml, doc/changelog.d/1448.maintenance.md
As title says. Testing it works and then completely removing from local workflow.
=> ci: check method implemented in Ansys actions

doc/changelog.d/1450.fixed.md, docker/linux/Dockerfile
Coming from @b-matteo's changes in server side.
None
=> fix: rename folders on Linux docker image according to new version

doc/changelog.d/1469.fixed.md, doc/source/conf.py
=> fix: solving intersphinx warnings on paths

doc/changelog.d/1489.maintenance.md, doc/source/conf.py
Avoid performing linkcheck on changelog file to save CI/CD time on unnecessary operations.
None
=> chore: avoid linkcheck on changelog (unnecessary)

doc/changelog.d/1511.documentation.md, doc/source/index.rst
Align landing page layout with UI/UX requirements
=> docs: align landing page layout with UI/UX requirements

doc/changelog.d/1527.documentation.md, doc/source/conf.py
Reduce the number of header elements.
None
=> docs: change max header links before more dropdown

.github/workflows/nightly_docker_test.yml, doc/changelog.d/1591.maintenance.md
As title says. This will allow each unstable image to move at its own pace
=> ci: decouple unstable image promotion

doc/changelog.d/1631.fixed.md, doc/source/getting_started/faq.rst
Adapts the FAQ on installation of the Geometry Service
Closes #1629
=> fix: FAQ on install

.github/workflows/ci_cd.yml, doc/changelog.d/1339.changed.md, doc/changelog.d/1637.fixed.md, docker/linux/coreservice/Dockerfile, docker/windows/coreservice/Dockerfile, docker/windows/dms/Dockerfile
When releasing 0.8.0, we encountered several issues... fixing them.
None
=> fix: release issues encountered

.github/workflows/ci_cd.yml, doc/changelog.d/1659.maintenance.md
=> ci: reverting semver package whitelist since problematic version is yanked

doc/changelog.d/1680.maintenance.md, src/ansys/geometry/core/modeler.py, tests/integration/conftest.py, tests/integration/test_design.py, tests/integration/test_geometry_commands.py
Ensure design closure on each test ending.
None
=> ci: ensure design is closed on test exit

.github/workflows/ci_cd.yml, .github/workflows/nightly_docker_test.yml, doc/changelog.d/1693.maintenance.md, doc/source/conf.py
Verify that the pygeometry-ci-2 runner works again.
Closes #1572
=> ci: use dedicate pygeometry-ci-2 runner

doc/changelog.d/1703.fixed.md, doc/source/examples/03_modeling/.gitignore, doc/source/examples/03_modeling/boolean_operations.mystnb, doc/source/examples/03_modeling/design_parameters.mystnb, src/ansys/geometry/core/connection/__init__.py, src/ansys/geometry/core/connection/conversions.py, src/ansys/geometry/core/designer/body.py, src/ansys/geometry/core/designer/component.py, src/ansys/geometry/core/designer/design.py, src/ansys/geometry/core/designer/geometry_commands.py, src/ansys/geometry/core/math/matrix.py, src/ansys/geometry/core/parameters/parameter.py, src/ansys/geometry/core/shapes/curves/nurbs.py, src/ansys/geometry/core/tools/problem_areas.py, src/ansys/geometry/core/tools/repair_tools.py, src/ansys/geometry/core/tools/unsupported.py, tests/integration/conftest.py, tests/integration/test_design.py, tests/integration/test_geometry_commands.py, tests/test_primitives.py
After technical review of the blitz branch, we are addressing the various comments here.
None
=> fix: tech review fixes for blitz branch

SECURITY.md, doc/changelog.d/1722.maintenance.md
=> chore: update SECURITY.md versions supported

doc/changelog.d/1745.test.md, tests/integration/test_design.py, tests/integration/test_geometry_commands.py, tests/integration/test_issues.py, tests/integration/test_prepare_tools.py
Activate 8 tests that were skipped
=> test: activate 8 linux tests

doc/changelog.d/1754.maintenance.md, src/ansys/geometry/core/connection/client.py, src/ansys/geometry/core/connection/launcher.py, src/ansys/geometry/core/designer/face.py, src/ansys/geometry/core/misc/checks.py, src/ansys/geometry/core/modeler.py, src/ansys/geometry/core/sketch/trapezoid.py, tests/test_misc_checks.py
Cleaning up old deprecations and adding more info on deprecation (version deprecated, removed in...)
Closes #1359
=> chore: clean up deprecation warning for trapezoid class and add more info on deprecation

doc/changelog.d/1798.test.md, doc/changelog.d/changelog_template.jinja, tests/integration/test_design.py
**This test will fail until we get a fix for the wrong name**
**We need to skip this test until we get a fix in.**
=> test: Skip test due to SC bug

doc/changelog.d/1804.test.md, tests/integration/test_prepare_tools.py
**Improve Share Topology test**
**Issue 1774.**
=> test: improve share topology test

.github/workflows/ci_cd.yml
Update action to use token
None
=> ci: update ansys/actions/release-github to use token

doc/changelog.d/1840.dependencies.md, pyproject.toml
Bump ansys-api-geometry on blitz branch
=> build: ansys api geometry 0.4.49

.github/workflows/ci_cd.yml, doc/changelog.d/1852.maintenance.md
Includes new features added in ansys/actions v8.2
- New changelog table layout
- Artifact attestation
- Test execution in random order
- Auto generate release notes on releases
None
=> ci: upgrading to new features in ansys/actions v8.2

doc/changelog.d/1855.maintenance.md, src/ansys/geometry/core/connection/backend.py, src/ansys/geometry/core/designer/component.py, src/ansys/geometry/core/designer/design.py, src/ansys/geometry/core/misc/auxiliary.py, src/ansys/geometry/core/modeler.py
Cleanup coming from the comments raised in #1853 
None
=> chore: cleanup blitz PR

SECURITY.md, doc/changelog.d/1857.maintenance.md, doc/source/assets.rst, doc/source/getting_started/installation.rst, pyproject.toml
=> chore: bump version number to 0.11.dev0

.github/workflows/ci_cd.yml, doc/changelog.d/1858.maintenance.md
This is solved in https://github.com/ansys/actions/pull/742 but we also need to fix the inputs here.
None
=> ci: fix release notes inputs

.github/workflows/ci_cd.yml, doc/changelog.d/1898.maintenance.md, pyproject.toml
Removing whitelisting from our actions
=> ci: remove whitelisting

doc/changelog.d/1925.fixed.md, src/ansys/geometry/core/_grpc/_services/_service.py, src/ansys/geometry/core/_grpc/_services/base/conversions.py, src/ansys/geometry/core/_grpc/_version.py, src/ansys/geometry/core/connection/client.py, src/ansys/geometry/core/designer/component.py, src/ansys/geometry/core/designer/design.py, src/ansys/geometry/core/designer/face.py, src/ansys/geometry/core/parameters/parameter.py, src/ansys/geometry/core/shapes/curves/nurbs.py, src/ansys/geometry/core/tools/repair_tools.py
As title says. Surfaced in #1924
=> fix: docstyle ordering

doc/changelog.d/1961.added.md, pyproject.toml
Switching to license metadata.
=> feat: use license metadata properly

doc/changelog.d/1965.documentation.md, doc/source/getting_started/installation.rst
Changing URL since redirect is happenning. Redirect also fails from time to time so this way we make it more robust.
=> docs: change python3statement url

.github/workflows/ci_cd.yml, .github/workflows/docker_cleanup.yml, .github/workflows/label.yml, .github/workflows/nightly_docker_test.yml
=> ci: bump ansys/actions to v9.0.12

doc/changelog.d/2060.documentation.md, doc/source/assets.rst, doc/source/getting_started/docker/windows_container.rst
Adding disclaimer to binaries repository
Closes #2020
=> docs: add proper disclaimer to binaries repository

tests/integration/conftest.py, tests/integration/test_design_export.py, tests/test_shapes.py
Test for failed glb export test
Round trip tests using open_file
=> test: bug fix test and round trip open file tests

doc/changelog.d/2147.test.md, tests/integration/test_design_import.py
We need to skip this test to promote the latest service build
2146
=> test: temp skip

doc/changelog.d/2267.added.md, src/ansys/geometry/core/_grpc/_services/_service.py, src/ansys/geometry/core/_grpc/_services/base/unsupported.py, src/ansys/geometry/core/_grpc/_services/v0/unsupported.py, src/ansys/geometry/core/_grpc/_services/v1/unsupported.py, src/ansys/geometry/core/tools/unsupported.py
Migration of the ``UnsupportedStub`` to _grpc layer
Related to #1817
=> feat: cleaning up usage of unsupported stub

.github/workflows/nightly_docker_test.yml, doc/changelog.d/2274.fixed.md
As title says - updating cards
=> fix: card message on failure

.github/workflows/ci_cd.yml, doc/changelog.d/2279.maintenance.md
Removing tracker testing temporarily
None
=> ci: remove tracker testing
