ansys/pyansys-geometry

src/ansys/geometry/core/connection/product_instance.py

The folder name was correct as per the unified installer

changed name according to unified installer

---

doc/source/getting_started/compatibility.rst
doc/source/getting_started/faq.rst

docs: improvements to faq and compatibility matrix

---

.github/workflows/ci_cd.yml
doc/source/assets.rst
doc/source/conf.py

Closes #768
* Avoid uploading wheelhouses to gh-pages branch (hits GitHub storage limit) - related to #764
* Change vars call throughout the workflow to env var (by means of the redefinition of the var to env) - related to #765

fix: avoid uploading docs assets(wheelhouse) and minor updates to workflow

---

src/ansys/geometry/core/connection/product_instance.py

Use socket.gethostname() instead of empty string to get an available port.

Secure get_available_port method.

---

CONTRIBUTORS.md
src/ansys/geometry/core/connection/product_instance.py

The method get_available_port is not contained in any calls and decorated with staticmethod therefore it is not callable. Removed

Remove staticmethod decorator

---

.github/workflows/ci_cd.yml

Due to the Licensing issues on the Linux container, we are skipping the Linux tests temporarily. This will have to be reactivated once the issues are solved

skip Linux testing - temp fix

---

src/ansys/geometry/core/connection/launcher.py
src/ansys/geometry/core/connection/product_instance.py

These changes allows to specify another logs folder for the ApiServer, different from the default one.

Add logs folder as variable to the launcher

---

pyproject.toml
src/ansys/geometry/core/designer/body.py
src/ansys/geometry/core/designer/design.py
tests/integration/test_design.py
tests/integration/test_design_import.py

feat: import surface body properly when reading design + boolean ops with multiple bodies

---

src/ansys/geometry/core/tools/repair_tools.py
tests/integration/test_repair_tools.py

instead of exposing body id strings, repair tool methods are working with body objects directly..

Refactoring repair tools

---

src/ansys/geometry/core/modeler.py
tests/integration/test_runscript.py

Defaults `script_args` to `{}`.
Closes  #870

fix: Add default dict to `run_discovery_script_file` 

---

src/ansys/geometry/core/plotting/plotter.py
src/ansys/geometry/core/plotting/plotter_helper.py

Edge picking was broken due to a change in the object I was checking. Now it is working.

fix: Broken edge picking

---

.pre-commit-config.yaml

As title says - current version is broken due to Reuse release

fix: update pre-commit hook

---

src/ansys/geometry/core/designer/design.py
src/ansys/geometry/core/materials/property.py

Coming from #947 
This PR will allow to read in Materials, MaterialProperties with unsupported MaterialPropertyType and units that are not registered within the PyAnsys Geometry codebase.
We should end up including full support for MaterialPropertyTypes and units but in the meantime this will allow to read all materials easily. Opening up a follow up issue.

feat: allow for "undefined" material types and units

---

doc/source/index.rst

On phone docs for the landing page look off. This should fix it.

docs: single column on phone docs

---

src/ansys/geometry/core/designer/design.py

Coming from @Alberto-DM - the warning message should not be logged as "Error :", since it can cause confusion.

fix: do not log warning message as error

---

tests/integration/test_design.py
tests/integration/test_design_import.py

Temporarily skip import/export tests in order to get the GeometryService update for security

Skip import/export tests to get DMS through

---

doc/Makefile
doc/make.bat
doc/source/conf.py
pyproject.toml

Stop using our custom sphinx-autoapi branch in favor of the official alpha release. This is blocked until https://github.com/ansys/ansys-sphinx-theme/pull/344 gets merged and a new minor release of our corporate theme is out.

doc: update to sphinx-autoapi==3.1.0a2 version

---

doc/source/conf.py

add the baseurl in conf.py for documentation redirection wrt to multiversion documentation.

fix: add the baseurl in conf.py

---

.github/workflows/ci_cd.yml

Continuation of #971. Ensures that both dev and stable are using the feat/seo-improvements branch.

ci: use feat/seo-improvements branch for doc-deploy

---

doc/make.bat
doc/source/conf.py

``jupytext`` through Python scripting was leading to failures when running on Windows mode
Follow up of #1002

fix: using jupytext through subprocess - fails on Windows otherwise

---

src/ansys/geometry/core/connection/launcher.py

Fix bug in ``launch_modeler`` function with automatic resolution of backend. SpaceClaim and Discovery were not being called.
No issue linked

fix: launch_modeler function had invalid/erroneous calls

---

sitemap.xml

Adding index.html pages to the subdirectories listed in our sitemap to enhance user experience and SEO. This is a PR to ``gh-pages`` branch.

fix: add `index.html` pages for the sub directories of sitemap

---

doc/.vale.ini
doc/changelog.d/1070.fixed.md
src/ansys/geometry/core/designer/component.py

Docstring says a sketch is accepted, but this is not true

fix: misleading docstring for sweep_chain()

---

doc/changelog.d/1076.fixed.md
src/ansys/geometry/core/connection/product_instance.py

Controlling usage of subprocess (only for Windows OS) and avoid using ``shell=True``.

fix: prepare_and_start_backend is only available on Windows

---

doc/changelog.d/1095.fixed.md
pyproject.toml
src/ansys/geometry/core/connection/client.py

Limiting to older versions of beartype (temporarily).
None

build: beartype upper limit on v0.18

---

.github/CODEOWNERS
doc/changelog.d/1098.changed.md

I believe you were being tagged EVERYWHERE  unnecessarily as reviewer @PipKat - sorry for that!

fix: removing @PipKat from *.md files - changelog fragments

---

doc/changelog.d/1103.fixed.md
src/ansys/geometry/core/modeler.py

Return type coming from ``run_discovery_script_file`` was ``ScalarMapContainer`` instead of ``dict``. Though they effectively behave in the same way, it is true that the type should be a dictionary since we should avoid returning gRPC objects to the end user.
Closes #1102

fix: return type should be dict and not ``ScalarMapContainer`` (grpc type)

---

.github/workflows/ci_cd.yml
.github/workflows/nightly_docker_test.yml
doc/changelog.d/1112.changed.md

As title says - upgrading to Python 3.12 (for self-hosted runners as well)

ci: main Python version update to 3.12

---

index.html
version/stable/index.html

Removes additional tags for canonical pages. Still investigating where this originates. The script in the `feat/seo-improvements` branch seems to be working fine locally. The rest of the pages only have one canonical link tag.

fix: canonical links included in documentation

---

doc/changelog.d/1123.fixed.md
doc/source/conf.py

As described in the issue
#1122

fix: solve issues with intersphinx when releasing

---

.github/workflows/ci_cd.yml
doc/changelog.d/1140.changed.md

As title says. Use default ``vale`` version

chore: use default vale version

---

CHANGELOG.md
doc/changelog.d/1154.miscellaneous.md

A link was incorrect within the `CHANGELOG.md` file.
None.

docs: fix link in `CHANGELOG.md`

---

doc/changelog.d/1171.fixed.md
pyproject.toml
src/ansys/geometry/core/connection/client.py
src/ansys/geometry/core/designer/edge.py
src/ansys/geometry/core/designer/face.py
src/ansys/geometry/core/misc/checks.py

Fixing 24R1 related issue due to GetSurface and GetCurve APIs
Closes #1170

fix: GetSurface and GetCurve not available prior to 24R2

---

doc/changelog.d/1173.added.md
doc/source/conf.py

Adding the ``semver`` package to intersphinx mapping: https://python-semver.readthedocs.io/en/latest/objects.inv

feat: add semver to intersphinx

---

.github/workflows/ci_cd.yml
doc/changelog.d/1174.changed.md
src/ansys/geometry/core/connection/client.py

Temporary workaround for times when the last release binaries are working but the ones on artifactory aren't

fix: allow to reuse last release binaries (if requested)

---

doc/changelog.d/1176.fixed.md
src/ansys/geometry/core/designer/edge.py
src/ansys/geometry/core/designer/face.py
src/ansys/geometry/core/plotting/plotter.py

New ``shape`` property is not available in 24R1... causing plotter to fail as well since the edges can't be plotted. This should fix the issues coming from it (delegating it to the previous API).

fix: start and end points for edge

---

doc/changelog.d/1182.added.md
src/ansys/geometry/core/connection/launcher.py

Allow the usage of product version on the Geometry Service launcher functions.
Closes #1181

feat: allow for ``product_version`` on geometry service launcher function

---

.github/workflows/ci_cd.yml
doc/changelog.d/1216.changed.md

As title says - implementing https://actions.docs.ansys.com/version/stable/migrations/release-pypi-trusted-publisher.html#release-pypi-trusted-publisher

ci: use Trusted Publisher for releasing package

---

.github/workflows/ci_cd.yml
doc/changelog.d/1223.changed.md

Avoid link verification issues on machines inside the Ansys network

ci: only run doc build on runners outside the ansys network

---

doc/changelog.d/1226.fixed.md
doc/source/conf.py
pyproject.toml

Fixes the interactive documentation after the integration of `ansys-tools-visualization-interface`.
Closes #1225

fix: Interactive documentation

---

doc/changelog.d/1227.added.md
doc/source/examples/01_getting_started/05_plotter_picker.mystnb
doc/source/examples/02_sketching/advanced_sketching_gears.mystnb
doc/source/examples/02_sketching/basic_usage.mystnb
doc/source/examples/03_modeling/boolean_operations.mystnb
doc/source/examples/04_applied/02_naca_fluent.mystnb
src/ansys/geometry/core/designer/body.py
src/ansys/geometry/core/designer/component.py
src/ansys/geometry/core/plotting/__init__.py
src/ansys/geometry/core/plotting/plotter.py
src/ansys/geometry/core/plotting/widgets/show_design_point.py
src/ansys/geometry/core/sketch/sketch.py
tests/integration/test_plotter.py

Renaming plotter class name
No issue linked

fix: rename ``GeomPlotter`` to ``GeometryPlotter``

---

doc/changelog.d/1257.fixed.md
pyproject.toml
src/ansys/geometry/core/plotting/plotter.py

Fixes shadowing caused by `visualization-interface`. Fixed in https://github.com/ansys/ansys-tools-visualization-interface/pull/75

fix: Rename built in shadowing variables

---

doc/changelog.d/1260.added.md
src/ansys/geometry/core/connection/launcher.py
src/ansys/geometry/core/connection/product_instance.py

Providing a way to control the client logs from the launcher methods
Closes #1220

feat: deprecating log_level and logs_folder + adding client log control

---

doc/changelog.d/1261.added.md
src/ansys/geometry/core/connection/launcher.py
src/ansys/geometry/core/connection/product_instance.py
src/ansys/geometry/core/designer/face.py
src/ansys/geometry/core/misc/__init__.py
src/ansys/geometry/core/misc/checks.py
src/ansys/geometry/core/plotting/plotter.py
tests/test_misc_checks.py

Adding deprecation decorators for methods and arguments
Closes #1259

feat: adding deprecation support for args and methods

---

doc/changelog.d/1264.fixed.md
src/ansys/geometry/core/shapes/surfaces/sphere.py

Potential bug... array comparison shouldn't be happening. You just want to verify whether the value is 0, to perform a 90º projection.

fix: unnecessary Point3D comparison

---

doc/changelog.d/1275.fixed.md
src/ansys/geometry/core/connection/conversions.py

fix: backticks breaking doc build after ruff linter

---

.pre-commit-config.yaml
doc/changelog.d/1276.changed.md

Bumping the ansys/pre-commit-hooks to increase speed

chore: bump pre-commit-hook version

---

doc/changelog.d/1289.fixed.md
src/ansys/geometry/core/connection/product_instance.py

As title says - this was causing the impossibility to launch SpaceClaim or Discovery with PyAnsys Geometry. Coming from #1274 ...

fix: manifest path should render as posix rather than uri

---

doc/changelog.d/1310.fixed.md
src/ansys/geometry/core/sketch/arc.py
tests/integration/test_issues.py

Problem related to the way default units are consumed inside the arc creation based on points.
Closes #1304

fix: default length units not being used properly on arc creation

---

doc/changelog.d/1311.added.md
src/ansys/geometry/core/designer/body.py
tests/integration/test_design.py

Provide the option to keep the "other" bodies passed when performing a bool operation. By default it will be false to support backward compatibility.
Closes #1302

feat: keep "other" bodies when performing bool operations

---

doc/changelog.d/1336.added.md
src/ansys/geometry/core/designer/component.py
tests/integration/test_design.py
tests/integration/test_issues.py

Rotation definition when revolving is now defined based on the axis passed: revolution axis and sketch plane normal axis. This allows to remove the "blocking condition" of coincident origins and equally aligned axis of reference in some sketches.
Closes #1309

feat: ``revolve_sketch`` rotation definition enhancement

---

.github/workflows/ci_cd.yml
.pre-commit-config.yaml
doc/changelog.d/1341.added.md
doc/source/assets.rst
doc/source/conf.py
doc/source/getting_started/installation.rst
pyproject.toml
tox.ini

Dropping support for Python 3.9 following SPEC-0 and ADR 21 (Ansys internal)
None

build: drop support for Python 3.9

---

doc/changelog.d/1375.added.md
src/ansys/geometry/core/modeler.py
tests/integration/conftest.py

We have the ``modeler.close()`` method but in order to be in line with the other PyAnsys libraries, we are also including ``modeler.exit()`` now. They will effectively perform the same calls.
Related to https://github.com/ansys/pyansys-geometry/discussions/1374

feat: add ``modeler.exit()`` method

---

doc/changelog.d/1385.added.md
src/ansys/geometry/core/connection/client.py
src/ansys/geometry/core/designer/design.py
src/ansys/geometry/core/modeler.py

As title says - some methods were only accepting strings and not pathlib.Path objects
Related to #1384

feat: accept pathlib.Path as input in missing methods

---

doc/changelog.d/1386.added.md
src/ansys/geometry/core/connection/launcher.py
src/ansys/geometry/core/connection/product_instance.py

Whenever we launch the Geometry Service locally (on Windows), we will make use of the APPDATA directory for Ansys products. Users should always have write permissions to it, and it will prevent from having some common issues like https://github.com/ansys/pyansys-geometry/discussions/1374#discussioncomment-10464047
Closes #1377

feat: default logs folder on Geometry Service started by Python at PUBLIC (Windows)

---

doc/changelog.d/1387.fixed.md
src/ansys/geometry/core/connection/launcher.py
src/ansys/geometry/core/connection/product_instance.py

After conversations with @b-matteo - environment variable ``ANS_DSCO_REMOTE_LOGS_FOLDER`` is only applicable for the Geometry Service. Removing it as a potential input for SpaceClaim and Discovery
None - but related to #1377

fix: remove ``server_logs_folder`` argument for Discovery and SpaceClaim

---

doc/changelog.d/1401.added.md
src/ansys/geometry/core/modeler.py
tests/integration/test_design.py
tests/integration/test_design_import.py

Allow retrieval of open designs easily through public attribute.
Closes #1400

feat: expose ``modeler.designs`` attribute

---

doc/changelog.d/1410.documentation.md
doc/source/examples/01_getting_started/05_plotter_picker.mystnb
doc/source/examples/02_sketching/advanced_sketching_gears.mystnb
doc/source/examples/02_sketching/dynamic_sketch_plane.mystnb
doc/source/examples/03_modeling/add_design_material.mystnb
doc/source/examples/03_modeling/boolean_operations.mystnb
doc/source/examples/03_modeling/design_organization.mystnb
doc/source/examples/03_modeling/design_tree.mystnb
doc/source/examples/03_modeling/export_design.mystnb
doc/source/examples/03_modeling/plate_with_hole.mystnb
doc/source/examples/03_modeling/revolving.mystnb
doc/source/examples/03_modeling/scale_map_mirror_bodies.mystnb
doc/source/examples/03_modeling/sweep_chain_profile.mystnb
doc/source/examples/03_modeling/tessellation_usage.mystnb
doc/source/examples/04_applied/01_naca_airfoils.mystnb
doc/source/examples/04_applied/02_naca_fluent.mystnb

Coming from the Ansys Lab team - we should adapt our examples so that they can also be easily consumed on Ansys Lab... and not only that but any user that wants to try them locally! Most of them were assuming that there was a running service in the backend - which is not the usual case.
None

docs: adapt examples to use launch_modeler instead of Modeler obj connection

---

doc/changelog.d/1416.added.md
src/ansys/geometry/core/connection/launcher.py
tests/integration/test_launcher_remote.py

Coming from an old request and to make it even more explicit for users.... Users can now benefit from the new "platform" argument when running on Ansys Lab to make it clear they want to use either the "windows" or the "linux" service. This is only available on Ansys Lab for now. If ``version`` is passed, this will take precedence since this is the expected argument for PyPIM
Closes #478

feat: allow for platform input when using Ansys Lab

---

doc/changelog.d/1417.added.md
src/ansys/geometry/core/connection/client.py

Ensuring the GrpcClient closure method gets called upon completion.
Closes #1415

feat: ensure GrpcClient class closure upon deletion

---

doc/changelog.d/1419.fixed.md
src/ansys/geometry/core/math/vector.py

As title says - once Numpy 1.X is not used anymore we can remove this.
None

fix: handle properly ``np.cross()`` - 2d ops deprecated in Numpy 2.X

---

README.rst
doc/changelog.d/1420.fixed.md

As title says - otherwise logo does not render on PyPI. See https://pypi.org/project/ansys-geometry-core/0.7.1/
See PyMechanical, where this is solved: https://pypi.org/project/ansys-mechanical-core/0.11.7/

fix: change logo link so that it renders properly on PyPI

---

.github/workflows/ci_cd.yml
doc/changelog.d/1423.maintenance.md

Binaries repo is using LFS which, by default, the actions don't check out for obvious reasons (+100Mb large files). Handling checkout only when needed on the pipeline. This default behavior has been modified recently in the ``actions/checkout@v4`` action.
None

ci: checkout LFS files from previous version to ensure upload

---

doc/changelog.d/1434.documentation.md
doc/source/examples.rst
pyproject.toml

This pull-request enables captions in the left sidebar of the example pages. The latest version of our corporate theme is required.

docs: add captions in examples toctrees

---

doc/changelog.d/1440.added.md
src/ansys/geometry/core/connection/product_instance.py

Prioritize the value of env var SPACECLAIM_MODE defined by the user, to the one defined by the library.
Closes #1439

feat: prioritize user-defined SPACECLAIM_MODE env var

---

.github/workflows/ci_cd.yml
.github/workflows/nightly_docker_test.yml
doc/changelog.d/1447.maintenance.md

Windows self-hosted runners experiencing issues with ``shell: bash`` commands. This will define the environment variable PYVISTA_OFF_SCREEN on behalf of the action, and we will skip the failing part as well.

ci: pyvista/setup-headless-display started failing

---

.github/dependabot.yml
.github/workflows/nightly_docker_test.yml
doc/changelog.d/1463.maintenance.md

* Making dependabot updates happen daily
* Promoting nightly builds to stable if tests pass
None

ci: unstable image promotion and dependabot daily updates

---

doc/changelog.d/1472.fixed.md
src/ansys/geometry/core/tools/prepare_tools.py

ShareTopology is already available in 24R2 - changing decorator
Discussion #1468

fix: ``share_topology`` is available on 24R2

---

doc/changelog.d/1471.fixed.md
src/ansys/geometry/core/tools/prepare_tools.py
tests/integration/test_prepare_tools.py

Bugs located in ``prepare_tools`` module regarding forward references and type checking. We cannot use ``check_input_types`` with forward references unless it's the class itself.
None

fix: ``check_input_types`` not working with forward refs

---

doc/changelog.d/1475.dependencies.md
pyproject.toml

As title says. Enabling PyData search by default

build: bump ansys-sphinx-theme to v1.1.3

---

doc/changelog.d/1478.fixed.md
doc/source/conf.py
pyproject.toml

With the new release of [ansys-sphinx-theme](https://pypi.org/project/ansys-sphinx-theme/), the name of the options need to be the same as the ones in [Fuse.js options](https://www.fusejs.io/api/options.html). This pull-request ensures that.

fix: static search options

---

doc/changelog.d/1486.fixed.md
src/ansys/geometry/core/connection/product_instance.py

When launching the Geometry Service with `launch_modeler`, respect the provided `product_version` keyword argument.
When launching with `mode="geometry_service"`, the latest installed Ansys version was always used. Notably, also when only an older version actually has the Geometry Service installed.

fix: respect product_version when launching geometry service

---

doc/changelog.d/1485.documentation.md
doc/source/conf.py

> This is completely optional, so feel free to discard and close.
This pull-request gets rid of the drop-down in the top navigation bar, accommodating all the headers before the drop-down comes in.

docs: avoid having a drop down in the top navigation bar

---

doc/changelog.d/1490.documentation.md
doc/source/conf.py
doc/source/contributing.rst
doc/source/examples/03_modeling/service_colors.mystnb

Provide docs on how to build an example and align previous examples as well. Also, provide capability to exclude cheat sheet build.
None

docs: provide information on how to build a single example

---

.github/workflows/docker_cleanup.yml
doc/changelog.d/1497.maintenance.md

As title says. Allowing new tags called ``windows-coreservice`` and ``windows-coreservice-unstable``

ci: allowing new tags for Windows Core Service

---

doc/changelog.d/1513.added.md
src/ansys/geometry/core/designer/body.py
src/ansys/geometry/core/designer/component.py
tests/integration/test_design.py

Allow for body caching if no new bodies have been added. This reduces the amount of time we spend on object creation...
None

feat: caching bodies to avoid unnecessary object creation

---

doc/changelog.d/1524.documentation.md
src/ansys/geometry/core/shapes/surfaces/plane.py

**fix typo in docstrings cylinder --> plane.**
nil

docs: typo with the docstrings

---

doc/changelog.d/1534.added.md
src/ansys/geometry/core/designer/component.py

Allow for additional strings when accepting extrude directions. Makes sense to also support these...
None

feat: allow for some additional extrusion direction names

---

doc/changelog.d/1544.dependencies.md
pyproject.toml

grpcio package upgrade contains breaking changes

build: limit upper version on grpcio & grpcio-health-checking to 1.68

---

doc/changelog.d/1548.added.md
doc/source/getting_started/local/index.rst
doc/source/getting_started/remote/index.rst
docker/build_docker_windows.py
src/ansys/geometry/core/connection/launcher.py
src/ansys/geometry/core/connection/product_instance.py
src/ansys/geometry/core/modeler.py

Allow the Ansys Student version to be considered as a potential option with the same version numbering as the normal versions (according to ansys-tools-path, student versions are negated).
Also taken the opportunity to "remove" support for 23R2 since it was very limited and restricted only to a specific PyAnsys Geometry minor version (0.2 and 0.3).
Closes #1526

feat: allow version input to automatically consider the nuances for the Ansys Student version

---

doc/changelog.d/1556.fixed.md
doc/source/conf.py
src/ansys/geometry/core/connection/docker_instance.py
src/ansys/geometry/core/connection/launcher.py
src/ansys/geometry/core/connection/product_instance.py
src/ansys/geometry/core/designer/body.py
src/ansys/geometry/core/designer/component.py
src/ansys/geometry/core/designer/design.py
src/ansys/geometry/core/designer/face.py
src/ansys/geometry/core/designer/part.py
src/ansys/geometry/core/math/bbox.py
src/ansys/geometry/core/math/misc.py
src/ansys/geometry/core/math/point.py
src/ansys/geometry/core/math/vector.py
src/ansys/geometry/core/misc/accuracy.py
src/ansys/geometry/core/misc/auxiliary.py
src/ansys/geometry/core/modeler.py
src/ansys/geometry/core/plotting/plotter.py
src/ansys/geometry/core/shapes/curves/line.py
src/ansys/geometry/core/shapes/parameterization.py
src/ansys/geometry/core/shapes/surfaces/cylinder.py
src/ansys/geometry/core/sketch/arc.py
src/ansys/geometry/core/sketch/circle.py
src/ansys/geometry/core/sketch/edge.py
src/ansys/geometry/core/sketch/ellipse.py
src/ansys/geometry/core/sketch/face.py
src/ansys/geometry/core/sketch/segment.py
src/ansys/geometry/core/sketch/sketch.py
src/ansys/geometry/core/tools/measurement_tools.py

After #1481 a lot of numpydoc warnings started to show up. Let's fix them whenever possible
None

fix: numpydoc warnings

---

doc/changelog.d/1559.added.md
src/ansys/geometry/core/connection/client.py

As title says - timeout for health check is adapted more intelligently by backing off to double the previous timeout... until we reach the timeout limit set by the user. This allows us to adapt to "slow connections" and also avoid exposing parameters. These parameters would be hard to control by users and not expected really.
Closes #1558 
At least the main problem in #1558 - we won't be exposing the parameter in the end.

feat: adapt health check timeout algorithm

---

.github/workflows/ci_cd.yml
.github/workflows/nightly_docker_test.yml
doc/changelog.d/1592.maintenance.md

Looking into saving resources... whenever the manifests for the unstable and stable images are the same, we should try to skip the execution of the unstable ones... no added value and really just consuming resources. Since we are low on VMs currently, we really need to look into saving as much as possible
None

ci: skip unnecessary stages when containers are the same

---

doc/changelog.d/1603.fixed.md
src/ansys/geometry/core/logger.py

Too many positional args were provided to `make_child_logger`.

fix: make_child_logger only takes 2 args.

---

doc/changelog.d/1604.maintenance.md
src/ansys/geometry/core/sketch/trapezoid.py

chore: Numpy is already imported at the top of the module.

---

SECURITY.md
doc/changelog.d/1605.documentation.md

As title says.
This will be used for all the other repos of our organization.

docs: Explain how to report a security issue.

---

doc/changelog.d/1623.added.md
src/ansys/geometry/core/designer/geometry_commands.py
tests/integration/test_geometry_commands.py

Create a full fillet (round) between a collection of faces.

feat: create a full fillet between multiple faces

---

doc/changelog.d/1627.added.md
doc/changelog.d/1628.added.md
src/ansys/geometry/core/designer/__init__.py
src/ansys/geometry/core/designer/body.py
src/ansys/geometry/core/designer/face.py
src/ansys/geometry/core/designer/geometry_commands.py
tests/integration/test_geometry_commands.py

Extrude existing faces, extrude faces up to other objects, setup face offset relationships between two faces.

feat: extrude existing faces, setup face offset relationships

---

doc/changelog.d/1638.added.md
pyproject.toml
src/ansys/geometry/core/designer/design.py
src/ansys/geometry/core/designer/geometry_commands.py
tests/integration/test_geometry_commands.py

Extrude existing edges a certain distance or up to another object.
Also fixed a bug with design cached bodies not clearing.

feat: extrude existing edges to create surface bodies

---

doc/changelog.d/1650.added.md
src/ansys/geometry/core/designer/component.py
tests/integration/test_design.py

Ability to create a surface body from a list of trimmed curves.

feat: surface body from trimmed curves

---

doc/changelog.d/1685.fixed.md
tests/integration/test_design_import.py

This change is to fix the test_open_file. We used to call set and get export id for whatever backend type we where testing against. Right now those apis are only implemented in CoreService based backends, so we should only use set and get export id against those.

fix: filter set export id to only CoreService based backends

---

doc/changelog.d/1690.fixed.md
src/ansys/geometry/core/modeler.py
src/ansys/geometry/core/tools/__init__.py
src/ansys/geometry/core/tools/unsupported.py
tests/integration/test_design_import.py

Relocate and clean unsupported module
None

fix: cleanup unsupported module

---

.github/workflows/ci_cd.yml
doc/changelog.d/1692.added.md
src/ansys/geometry/core/connection/backend.py
src/ansys/geometry/core/connection/client.py
src/ansys/geometry/core/connection/product_instance.py
src/ansys/geometry/core/modeler.py
tests/integration/conftest.py
tests/integration/test_design.py
tests/integration/test_design_export.py
tests/integration/test_design_import.py
tests/integration/test_issues.py
tests/integration/test_measurement_tools.py
tests/integration/test_prepare_tools.py
tests/integration/test_repair_tools.py
tests/integration/test_runscript.py
tests/integration/test_tessellation.py
tests/integration/test_trimmed_geometry.py

Implement the 3 new backend types: Discovery Headless, CoreService on Linux and CoreService on Windows
Implement a method to determine whether the backend if of CoreService Kind
Rename skip_if_linux method skip_if_core_service
adapt comments

feat: is_core_service BackendType static method

---

doc/changelog.d/1691.fixed.md
tests/integration/test_design.py
tests/integration/test_design_export.py

Skip export tests for formats not yet implemented into CoreService

fix: disable unimplemented tests

---

doc/changelog.d/1702.maintenance.md
pyproject.toml

Information associated to changes of type 'documentation' and 'maintenance' is duplicated.
None

chore: remove towncrier info duplicates

---

doc/changelog.d/1707.added.md
src/ansys/geometry/core/designer/design.py
tests/integration/test_design_import.py

- Removed temporary design in insert_file to avoid multiple designs being active at once
- Activated tests to verify design is active

feat: design activation changes

---

doc/changelog.d/1714.fixed.md
tests/integration/test_design.py

I added support on CoreService, so the test skip can be removed now.

fix: support body mirror on linux

---

doc/changelog.d/1715.fixed.md
src/ansys/geometry/core/designer/body.py

Previously the plane for curves to imprint or project was hardcoded as XY on the backend. I changed this to supply it from the sketch.
#1622

fix: use sketch plane for imprint/project curves

---

doc/changelog.d/1714.fixed.md
doc/source/getting_started/local/index.rst
src/ansys/geometry/core/connection/product_instance.py
tests/integration/test_design.py

Allow the option to define ANSYS_GEOMETRY_SERVICE_ROOT envar to provide path to CoreService executable instead of assuming the unified install.

feat: launch core service from envar

---

CONTRIBUTING.md
doc/changelog.d/1730.documentation.md

The link was missing `version`. Note that you can also use `stable` instead of `dev` 😄 
None

docs: update CONTRIBUTING.md

---

.github/workflows/docker_cleanup.yml
doc/changelog.d/1739.maintenance.md

Keeping whatever image the Simba team is using internally.

ci: keep simba-plugin-geometry tag

---

doc/changelog.d/1740.added.md
src/ansys/geometry/core/__init__.py
src/ansys/geometry/core/connection/client.py
src/ansys/geometry/core/designer/design.py
src/ansys/geometry/core/misc/checks.py
src/ansys/geometry/core/modeler.py
tests/integration/conftest.py
tests/integration/test_design.py
tests/integration/test_design_import.py

A single design instance per Modeler object is handled. If a new design is requested, the old design is closed. We are also being conservative and checking that if you use an object belonging to an old design, we are still checking whether the design is active or not. With #1721 we lost this capability. This implementation makes it more robust
Closes #1710

feat: conservative approach to single design per modeler

---

doc/changelog.d/1758.fixed.md
docker/linux/coreservice/Dockerfile

Issues with Linux docker image build due to missing dependency
None

fix: Linux Core Service docker file was missing a dependency

---

.github/labeler.yml
doc/changelog.d/1776.fixed.md

Typo in the documentation labeler
-

fix: typo in labeler.yml file

---

doc/changelog.d/1783.dependencies.md
pyproject.toml

Following issues with trusted publisher listed in https://github.com/ansys/actions/issues/687 - we need to limit the flit version used to build the project. This is a temporary workaround until we properly fix this issue.
None

build: temporary workaround for using trusted publisher approach

---

doc/changelog.d/1794.fixed.md
tests/integration/test_plotter.py

Flaky test due to face color assignment by order on list retrieval. This fixes it by looking at the normal of the face.
None

fix: flaky color test due to random face assignment

---

.github/workflows/ci_cd.yml
doc/changelog.d/1808.fixed.md
doc/source/index.rst
src/ansys/geometry/core/sketch/sketch.py
tests/integration/test_issues.py

Translation of sketches wasn't being handled properly. Now it should be consistent.
Closes #1807

fix: translating sketch issues when using a custom default unit

---

doc/changelog.d/1816.fixed.md
src/ansys/geometry/core/designer/edge.py
src/ansys/geometry/core/designer/face.py
src/ansys/geometry/core/shapes/curves/trimmed_curve.py
tests/integration/test_issues.py

Edge start and end values were not being mapped correctly. They should be using the server length when converted.
Closes #1813

fix: edge start and end were not being mapped correctly

---

.github/workflows/ci_cd.yml
.github/workflows/docker_ansyslab_windows.yml
.github/workflows/nightly_docker_test.yml
doc/Makefile
doc/changelog.d/1812.maintenance.md
doc/source/cheatsheet/.gitignore
doc/source/cheatsheet/cheat_sheet.qmd
doc/source/examples/03_modeling/chamfer.mystnb
doc/source/examples/03_modeling/design_tree.mystnb
doc/source/examples/03_modeling/export_design.mystnb
doc/source/examples/04_applied/02_naca_fluent.mystnb
pyproject.toml
src/ansys/geometry/core/designer/body.py

Removing DMS from CI/CD pipelines and using Core Service containers only.
None

ci: remove DMS from pipelines and use core service images only

---

doc/changelog.d/1850.fixed.md
src/ansys/geometry/core/designer/body.py
src/ansys/geometry/core/designer/component.py
src/ansys/geometry/core/designer/face.py
src/ansys/geometry/core/misc/__init__.py
src/ansys/geometry/core/modeler.py

Missing exposure of the tessellation options. Face and components were not able to control them.
Related to #1328

fix: tessellation options were not extended to component/face methods

---

doc/changelog.d/1871.test.md
tests/integration/test_design.py

- re-enabled portion of named_selection test testing for beam contents after server-side fix
#1868

test: issue 1868 (named selection beams testing)

---

doc/changelog.d/1882.added.md
src/ansys/geometry/core/_grpc/_services/_service.py
src/ansys/geometry/core/_grpc/_services/base/dbuapplication.py
src/ansys/geometry/core/_grpc/_services/v0/admin.py
src/ansys/geometry/core/_grpc/_services/v0/bodies.py
src/ansys/geometry/core/_grpc/_services/v0/dbuapplication.py
src/ansys/geometry/core/_grpc/_services/v1/bodies.py
src/ansys/geometry/core/_grpc/_services/v1/dbuapplication.py
src/ansys/geometry/core/modeler.py
tests/integration/test_runscript.py

Moves the DbuApplication stub to the new gRPC architecture
Related to #1817

feat: DbuApplication stub relocation

---

.github/workflows/ci_cd.yml
doc/changelog.d/1902.maintenance.md

Released docs should depend on PyPI and GH releases going through

ci: make doc releases dependent on GH and PyPI release

---

doc/changelog.d/1916.fixed.md
src/ansys/geometry/core/designer/body.py
src/ansys/geometry/core/plotting/plotter.py

API call ``is_suppressed`` is not available until 25R2.
None

fix: is_suppressed is not available until 25R2

---

.github/workflows/ci_cd.yml
.github/workflows/nightly_docker_test.yml
doc/changelog.d/1924.dependencies.md
doc/changelog.d/1925.fixed.md
pyproject.toml
src/ansys/geometry/core/_grpc/_services/_service.py
src/ansys/geometry/core/_grpc/_services/base/conversions.py
src/ansys/geometry/core/_grpc/_version.py
src/ansys/geometry/core/connection/client.py
src/ansys/geometry/core/designer/component.py
src/ansys/geometry/core/designer/design.py
src/ansys/geometry/core/designer/face.py
src/ansys/geometry/core/parameters/parameter.py
src/ansys/geometry/core/shapes/curves/nurbs.py
src/ansys/geometry/core/sketch/ellipse.py
src/ansys/geometry/core/sketch/polygon.py
src/ansys/geometry/core/sketch/sketch.py
src/ansys/geometry/core/tools/repair_tools.py
tests/conftest.py
tests/integration/test_design.py
tests/integration/test_plotter.py
tests/integration/test_tessellation.py

Supporting new PyVista and VTK versions -- this enables the usage of Python 3.13 across the board on CI/CD (docs build, main testing etc.)
Closes #1585

build: bump PyVista and VTK versions (support Python 3.13)

---

.github/workflows/nightly_docker_test.yml
doc/changelog.d/1931.maintenance.md

Unstable builds are failing for Linux because we were missing the headless display configuration. Setting it properly

ci: fix unstable workflows for Linux (missing headless display)

---

doc/changelog.d/1932.fixed.md
src/ansys/geometry/core/connection/product_instance.py

Issues appearing with new installation -- apparently the ``Native`` folder is different for Windows and Linux on local installations.

fix: adapt Native folder path for Linux and Windows

---

.github/workflows/ci_cd.yml
.github/workflows/nightly_docker_test.yml
doc/changelog.d/1934.maintenance.md

Using ``pyvista/setup-headless-display-action`` instead of private fork

ci: use v4 of pyvista/setup-headless-display-action

---

doc/changelog.d/1943.added.md
src/ansys/geometry/core/_grpc/_services/_service.py
src/ansys/geometry/core/_grpc/_services/base/admin.py
src/ansys/geometry/core/_grpc/_services/base/bodies.py
src/ansys/geometry/core/_grpc/_services/base/coordinate_systems.py
src/ansys/geometry/core/_grpc/_services/base/driving_dimensions.py
src/ansys/geometry/core/_grpc/_services/base/measurement_tools.py
src/ansys/geometry/core/_grpc/_services/base/prepare_tools.py
src/ansys/geometry/core/_grpc/_services/v0/conversions.py
src/ansys/geometry/core/_grpc/_services/v0/coordinate_systems.py
src/ansys/geometry/core/_grpc/_services/v1/coordinate_systems.py
src/ansys/geometry/core/designer/coordinate_system.py

Moves the CoordinateSystemStub to the ``_grpc`` layer.
Some extra docstring fixes are performed
Related to #1817

feat: move coordinate systems stub to grpc layer

---

doc/changelog.d/1957.documentation.md
doc/source/conf.py

Stackoverflow links now requiere human authentication. Ignoring their verification. Surfaced in #1956

docs: ignore stackoverflow link

---

doc/changelog.d/1958.fixed.md
src/ansys/geometry/core/connection/product_instance.py

Seems like ``LD_LIBRARY_PATH`` (on Linux) and ``PATH`` (on Windows) need to have ``CADIntegration/bin`` defined... Also, prepending to both ``LD_LIBRARY_PATH`` and ``PATH`` to avoid import resolution issues
Closes #1955

fix: core service launcher missing CADIntegration bin folder in path

---

.github/workflows/nightly_docker_test.yml

Trigger more unstable image updates

ci: trigger unstable image updates more frequently

---

doc/changelog.d/1970.fixed.md
doc/source/examples/01_getting_started/05_plotter_picker.mystnb

fix: myst warning -- all cells must be of same type

---

.github/workflows/ci_cd.yml
.github/workflows/docker_cleanup.yml
.github/workflows/label.yml
.github/workflows/nightly_docker_test.yml
doc/changelog.d/1985.maintenance.md

After the rollback on the actions, we need to revert to the old version

ci: revert ansys/actions release

---

doc/changelog.d/1998.added.md
src/ansys/geometry/core/connection/launcher.py
src/ansys/geometry/core/connection/product_instance.py

Coming from user request to enhance UX. We should deprecate the "product_version" input and just simplify it to "version". Also, str and int should be allowed as input.

feat: deprecating ``product_version`` in favor of ``version``

---

.github/codeql-config.yml
.github/workflows/ci_cd.yml
.github/workflows/nightly_docker_test.yml
doc/changelog.d/2016.maintenance.md
tests/integration/files/disco_scripts/failing_script.py

ci: improving CodeQL

---

doc/changelog.d/2032.fixed.md
src/ansys/geometry/core/plotting/plotter.py

``export_glb`` requires that the actor is a single Polydata. Multiblock's are not handled properly by PyVista's export_gltf function.
Closes #2030

fix: make sure export_glb is handling a single Polydata object

---

doc/changelog.d/2054.dependencies.md
pyproject.toml

After the ``ansys-tools-visualization-interface`` 0.10.0 release, we are seeing plenty of failures on our tests. Limiting the minor version until its handled...

build: limiting ansys-tools-visualization-interface

---

.github/workflows/ci_cd.yml
doc/changelog.d/2114.maintenance.md
docker/build_docker_windows.py

Using the 261 location from artifactory and cleaning up Docker builder script

ci: using proper artifactory location

---

doc/changelog.d/2119.maintenance.md
doc/source/assets.rst
doc/source/getting_started/installation.rst
pyproject.toml

chore: bump minor version in main

---

doc/changelog.d/2142.test.md
tests/test_primitives.py

added test for NURBSCurve lengths that was missing before

test: nurbs length test

---

.github/workflows/backwards_compatibility.yml
doc/changelog.d/2168.maintenance.md

Problems observed with 25.1 image. Reverting checks temporarily. Once https://github.com/ansys/pyansys-geometry/issues/2167 is solved, we can reactivate them

ci: remove temporarily 25.1 backwards compatibility checks

---

doc/changelog.d/2202.fixed.md
tests/integration/conftest.py
tests/integration/test_design_export.py

Add skip_if_discovery method
skip export tests for unsupported formats in Discovery
**Please provide a brief description of the changes made in this pull request.**
Skip unsupported formats when testing against Discovery
https://github.com/ansys/pyansys-geometry/discussions/2201

fix: add skip_if_discovery method
